### ISSUE TITLE
`ngram_collocations` broken because of quanteda API changes

### ISSUE THREAD

**Issue by trinker** [trinker/termco#41]
See https://github.com/kbenoit/quanteda/issues/688

This gives similar behavior to `quanteda::collocations`:

```
library(quanteda)

txt <- c("This is software testing: looking for (word) pairs the dog! peas and carrots  
         This [is] a software testing again. For. the dog want the book peas and carrots ",
         "Here: this is more Software Testing, want the book looking again for word pairs. peas and carrots ")

toks <- quanteda::tokens(txt, remove_punct = TRUE)

## does 2 and 3 grams (keep or use old behavior)?
ngrams <- lapply(c('lr', 'chi2', 'pmi', 'dice'), function(x){
    quanteda::textstat_collocations(toks, method = x)
})


Reduce(function(x, y) dplyr::left_join(x, y, by=c('collocation', 'count')), ngrams)
```

**Comment by trinker** [comment]
depending on how this is fixed in quanteda the following may need to be addressed as well. https://github.com/kbenoit/quanteda/issues/736

![image](https://cloud.githubusercontent.com/assets/1763278/26135145/95486978-3a81-11e7-9c93-d7b455dd704e.png)

`quanteda::textstat_collocations(` returns a factor for collocation column that I have to manually convert to character.

**Comment by kbenoit** [comment]
Works now that https://github.com/kbenoit/quanteda/issues/736 has been solved. We previously had the argument `method = "all"` ... this suggests we should bring it back?

**Comment by trinker** [comment]
@kbenoit yes for me because I like to compare metrics.  I'm guessing (without looking at the code) that the expensive part timewise is the extraction of collocations and counts.  After that the associated metrics are probably cheap to compute.

**Comment by trinker** [comment]
@kbenoit any word on you're team is going to re-implement the ` method = "all"`.  My approach is a dog using `Reduce`

**Comment by kbenoit** [comment]
We'll do that soon - are working on that function this week, but it turns out our computations for n>2 are incorrect. It's a lot trickier than we thought and we are actually writing a statistical paper to sort out the mess.

**Comment by trinker** [comment]
Version .99 of quanteda brings new API changes that break the fix.  `textstat_collocations` now only uses a lamda method and has difficulty if a vector has an empty element: https://github.com/kbenoit/quanteda/issues/940

Fix after a quanteda member responds to the issue

**Comment by kbenoit** [comment]
We are working on this (and a paper associated with it) because we are thinking that lambda is the best method. But more importantly, for G^2 and chi^2 we need the expected counts under a specific model, and this can only be fitted through iterative proportional fitting.  (Meaning: the expected counts we had in earlier versions used the wrong independence model.) We're trying to make this fast enough for production use.  https://github.com/kbenoit/quanteda/issues/924

**Comment by trinker** [comment]
As of 2018-02-01...


```
Warning message:
Arguments remove_punct, remove_symbols not used. 
```

Figure out why
